#ifndef _OPS_H
#define _OPS_H

enum {
	USBTINY_ECHO = 0,
	USBTINY_READ = 1,
	TEST_DEMO    = 2,
	TEST_IRTO7SEG = 3,
	GENIO_SET_PORT_A_DIR   = 0x10,
	GENIO_GET_PORT_A_PIN_D = 0x11,
	GENIO_SET_PORT_A_PIN_D = 0x12,
	GENIO_GET_PORT_A_PIN_A = 0x13,
	GENIO_SET_PORT_A_7SEG  = 0x19,
	GENIO_SET_PORT_A       = 0x1A,

	GENIO_SET_PORT_C_DIR   = 0x20,
	GENIO_GET_PORT_C_PIN_D = 0x21,
	GENIO_SET_PORT_C_PIN_D = 0x22,
	GENIO_SET_PORT_C_7SEG  = 0x29,
	GENIO_SET_PORT_C       = 0x2A,

	GENIO_SET_PWM          = 0xA0
};

#endif
